" shared baseline for Vim and Neovim
source $CONFIG_HOME/vim/settings/options.vim
source $CONFIG_HOME/vim/settings/keymaps.vim
source $CONFIG_HOME/vim/settings/filetypes.vim
source $CONFIG_HOME/vim/settings/statusline.vim

set runtimepath+=$CONFIG_HOME/vim
set runtimepath+=$DATA_HOME/vim

if has('nvim')
	finish
endif

" load vim specific plugins
source $CONFIG_HOME/vim/settings/plugins.vim

" configure Vim's adapter for the shared language servers
source $CONFIG_HOME/vim/settings/lsp.vim

" follow the terminal/system appearance
source $CONFIG_HOME/vim/settings/colors.vim

" Prevent screen clearing issues in certain terminals
let &t_ut=''

