#!/usr/bin/env sh

# load the scripting addition manually
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# general space
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# window behavior
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.5
yabai -m config window_topmost               on
yabai -m config window_placement             second_child

# window style
yabai -m config window_shadow                on
#       border
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff055275
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
#       opacity
yabai -m config window_opacity               on
yabai -m config window_opacity_duration       0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85

# mouse
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

## rules
yabai -m rule --add label="og float" \
    app='^(System Preferences|App Store|Music|Mail|Photos|Contacts|Calendar|Reminders|Notes|Bitwarden|Pixelmator Pro)$' \
    manage=off opacity=1.0 border=off
yabai -m rule --add label="full opacity" \
    app='^(Safari|Firefox)$' \
    opacity=1.0
yabai -m rule --add label="full screen" \
    app='^(Pixelmator Pro)$' \
    native-fullscreen=on
yabai -m rule --add label="terminal opacity" app="^Terminal$"
    opacity=0.92

